<script setup>
import {
  ref,
  onMounted,
  onUnmounted,
  computed,
  watch,
  reactive,
  watchEffect,
  onBeforeMount,
} from "vue";
import { xmlToSubtitle } from "../../../composables/xmlToSubtitle";
import { useDetailVideoStore } from "../../../stores/useDetailVideo";
import { useSettingsStore } from "../../../stores/useSettings";
const { SettingsState } = useSettingsStore();
const { state } = useDetailVideoStore();

const props = defineProps({
  qualityVideos: Array,
  video: Object,
  substileName: String,
});

const slowOptions = reactive([
  {
    id: 1,
    value: "0.25",
  },
  {
    id: 2,
    value: "0.5",
  },
  {
    id: 3,
    value: "0.75",
  },
  {
    id: 4,
    value: "Chuẩn",
  },
  {
    id: 5,
    value: "1.25",
  },
  {
    id: 6,
    value: "1.5",
  },
  {
    id: 7,
    value: "1.75",
  },
  {
    id: 8,
    value: "2.0",
  },
]);
const isMenuTabs = ref(true);
const isSettings = ref(false);
const isQuality = ref(false);
const isSpeed = ref(false);
const isSubtitles = ref(false);
const indexQuality = state.isDetailVideos?.videoStreams.find(
  (video) => video.quality === "480p"
);
const currentQuality = ref(indexQuality.quality);
watchEffect(() => {
  currentQuality.value = indexQuality.quality;
});
if (state.isDetailVideos.livestream) {
  currentQuality.value = null;
}
const isAutoQuality = ref(true);
const currentPlaybackrate = ref("Chuẩn");
const substitleCollection = ref([]);
const currentSubstitle = ref("Tắt");

watch(
  () => props.substileName,
  (newValue, oldValue) => {
    if (newValue) {
      currentSubstitle.value = newValue;
    } else {
      currentSubstitle.value = "Tắt";
    }
  }
);

const showSubtitles = () => {
  isSubtitles.value = true;
  isMenuTabs.value = false;
};
const closeSubtitles = () => {
  isSubtitles.value = false;
  isMenuTabs.value = true;
};
const showSpeed = () => {
  isSpeed.value = true;
  isMenuTabs.value = false;
};
const closeSpeed = () => {
  isSpeed.value = false;
  isMenuTabs.value = true;
};
const showQuality = () => {
  isQuality.value = true;
  isMenuTabs.value = false;
};
const closeQuality = () => {
  isQuality.value = false;
  isMenuTabs.value = true;
};
const showSettings = () => {
  isSettings.value = !isSettings.value;
  isMenuTabs.value = true;
  isQuality.value = false;
  isSpeed.value = false;
  isSubtitles.value = false;
};
const TurnOffSubstitle = () => {
  SettingsState.isOpenSubstile = false;
  currentSubstitle.value = "Tắt";
  showSettings();
};

const emit = defineEmits();

const handleSelectQualityVideo = (item) => {
  indexQuality.quality = item.quality;
  isAutoQuality.value = false;
  showSettings();
  emit("select-quality", item);
};

const HandleChangeVideoSpeed = (option) => {
  const playBackRateSpeed = option;
  currentPlaybackrate.value = option;
  showSettings();
  emit("select-playbackrate", playBackRateSpeed);
};
const HandleSelectSubstitles = async (substitle, index) => {
  SettingsState.isOpenSubstile = true;
  currentSubstitle.value = substitle.name;
  if (substitle.autoGenerated === true) {
    currentSubstitle.value = `${substitle.name} (tự động)`;
  }
  showSettings();
  const res = await fetch(substitle.url);
  substitleCollection.value = xmlToSubtitle(await res.text());
  emit("select-substitle", substitleCollection.value, index);
};
</script>

<template>
  <div class="max-w-[48px] max-h-[48px] ml-[10px] cursor-pointer">
    <div class="relative z-20">
      <div
        class="transition duration-200 ease-in"
        :class="{ 'rotate-45': isSettings }"
        @click="showSettings"
      >
        <svg height="100%" version="1.1" viewBox="0 0 36 36" width="100%">
          <use class="ytp-svg-shadow" xlink:href="#ytp-id-19"></use>
          <path
            d="m 23.94,18.78 c .03,-0.25 .05,-0.51 .05,-0.78 0,-0.27 -0.02,-0.52 -0.05,-0.78 l 1.68,-1.32 c .15,-0.12 .19,-0.33 .09,-0.51 l -1.6,-2.76 c -0.09,-0.17 -0.31,-0.24 -0.48,-0.17 l -1.99,.8 c -0.41,-0.32 -0.86,-0.58 -1.35,-0.78 l -0.30,-2.12 c -0.02,-0.19 -0.19,-0.33 -0.39,-0.33 l -3.2,0 c -0.2,0 -0.36,.14 -0.39,.33 l -0.30,2.12 c -0.48,.2 -0.93,.47 -1.35,.78 l -1.99,-0.8 c -0.18,-0.07 -0.39,0 -0.48,.17 l -1.6,2.76 c -0.10,.17 -0.05,.39 .09,.51 l 1.68,1.32 c -0.03,.25 -0.05,.52 -0.05,.78 0,.26 .02,.52 .05,.78 l -1.68,1.32 c -0.15,.12 -0.19,.33 -0.09,.51 l 1.6,2.76 c .09,.17 .31,.24 .48,.17 l 1.99,-0.8 c .41,.32 .86,.58 1.35,.78 l .30,2.12 c .02,.19 .19,.33 .39,.33 l 3.2,0 c .2,0 .36,-0.14 .39,-0.33 l .30,-2.12 c .48,-0.2 .93,-0.47 1.35,-0.78 l 1.99,.8 c .18,.07 .39,0 .48,-0.17 l 1.6,-2.76 c .09,-0.17 .05,-0.39 -0.09,-0.51 l -1.68,-1.32 0,0 z m -5.94,2.01 c -1.54,0 -2.8,-1.25 -2.8,-2.8 0,-1.54 1.25,-2.8 2.8,-2.8 1.54,0 2.8,1.25 2.8,2.8 0,1.54 -1.25,2.8 -2.8,2.8 l 0,0 z"
            fill="#fff"
            id="ytp-id-19"
          ></path>
        </svg>
      </div>
      <span
        v-if="currentQuality === '2160p' || currentQuality === '2160p60'"
        class="bg-[#f00] text-white px-[2px] h-[12px] text-[9px] absolute flex items-center justify-center top-[3px] z-50 font-bold right-0 touch-none"
        >4K</span
      >
      <span
        v-if="currentQuality === '1440p' || currentQuality === '1440p60'"
        class="bg-[#f00] text-white px-[2px] h-[12px] text-[9px] absolute flex items-center justify-center top-[3px] z-50 font-bold right-0 touch-none"
        >2K</span
      >
      <span
        v-if="currentQuality === '1080p' || currentQuality === '1080p60'"
        class="bg-[#f00] text-white px-[2px] h-[12px] text-[9px] absolute flex items-center justify-center top-[3px] z-50 font-bold right-0 touch-none"
        >HD</span
      >
    </div>
    <div
      class="w-[320px] z-40 bg-[#303030bd] absolute h-auto bottom-[80px] right-[20px] py-2 rounded-lg opacity-0 invisible"
      :class="{
        '!opacity-100 !visible': isSettings,
        '!w-[280px]': isQuality,
        '!w-[260px]': isSpeed,
        '!w-[260px]': isSubtitles,
      }"
    >
      <div v-if="isMenuTabs">
        <div
          class="w-full h-[45px] flex items-center justify-between px-4 hover:bg-[#686868] transition-all"
          @click="showSubtitles"
        >
          <div class="flex items-center">
            <div class="mr-[10px]">
              <svg height="24" viewBox="0 0 24 24" width="24">
                <path
                  d="M5,11h2v2H5V11z M15,15H5v2h10V15z M19,15h-2v2h2V15z M19,11H9v2h10V11z M22,6H2v14h20V6z M3,7h18v12H3V7z"
                  fill="white"
                ></path>
              </svg>
            </div>
            <p class="text-white text-[15px] font-roboto font-medium">Phụ đề</p>
          </div>
          <div class="flex items-center">
            <p class="text-[#d1d1d1] text-[14px] font-roboto font-medium">
              {{ currentSubstitle }}
            </p>
            <div>
              <svg
                height="24"
                viewBox="0 0 24 24"
                width="24"
                focusable="false"
                style="
                  pointer-events: none;
                  display: block;
                  width: 100%;
                  height: 100%;
                  transform: translateY(1px);
                "
              >
                <path
                  fill="#fff"
                  d="m9.4 18.4-.7-.7 5.6-5.6-5.7-5.7.7-.7 6.4 6.4-6.3 6.3z"
                ></path>
              </svg>
            </div>
          </div>
        </div>
        <div
          class="w-full h-[45px] flex items-center justify-between px-4 hover:bg-[#686868] transition-all"
          @click="showSpeed"
        >
          <div class="flex items-center">
            <div class="mr-[10px]">
              <svg height="24" viewBox="0 0 24 24" width="24">
                <path
                  d="M10,8v8l6-4L10,8L10,8z M6.3,5L5.7,4.2C7.2,3,9,2.2,11,2l0.1,1C9.3,3.2,7.7,3.9,6.3,5z            M5,6.3L4.2,5.7C3,7.2,2.2,9,2,11 l1,.1C3.2,9.3,3.9,7.7,5,6.3z            M5,17.7c-1.1-1.4-1.8-3.1-2-4.8L2,13c0.2,2,1,3.8,2.2,5.4L5,17.7z            M11.1,21c-1.8-0.2-3.4-0.9-4.8-2 l-0.6,.8C7.2,21,9,21.8,11,22L11.1,21z            M22,12c0-5.2-3.9-9.4-9-10l-0.1,1c4.6,.5,8.1,4.3,8.1,9s-3.5,8.5-8.1,9l0.1,1 C18.2,21.5,22,17.2,22,12z"
                  fill="white"
                ></path>
              </svg>
            </div>
            <p class="text-white text-[15px] font-roboto font-medium">
              Tốc độ phát
            </p>
          </div>
          <div class="flex items-center">
            <p class="text-[#d1d1d1] text-[15px] font-roboto font-medium">
              {{ currentPlaybackrate }}
            </p>
            <div>
              <svg
                height="24"
                viewBox="0 0 24 24"
                width="24"
                focusable="false"
                style="
                  pointer-events: none;
                  display: block;
                  width: 100%;
                  height: 100%;
                  transform: translateY(1px);
                "
              >
                <path
                  fill="#fff"
                  d="m9.4 18.4-.7-.7 5.6-5.6-5.7-5.7.7-.7 6.4 6.4-6.3 6.3z"
                ></path>
              </svg>
            </div>
          </div>
        </div>
        <div
          @click="showQuality"
          class="w-full h-[45px] flex items-center justify-between px-4 hover:bg-[#686868] transition-all"
        >
          <div class="flex items-center">
            <div class="mr-[10px]">
              <svg height="24" viewBox="0 0 24 24" width="24">
                <path
                  d="M15,17h6v1h-6V17z M11,17H3v1h8v2h1v-2v-1v-2h-1V17z M14,8h1V6V5V3h-1v2H3v1h11V8z            M18,5v1h3V5H18z M6,14h1v-2v-1V9H6v2H3v1 h3V14z M10,12h11v-1H10V12z"
                  fill="white"
                ></path>
              </svg>
            </div>
            <p class="text-white text-[14px] font-roboto font-medium">
              Chất lượng
            </p>
          </div>
          <div class="flex items-center">
            <div>
              <p
                v-if="isAutoQuality"
                class="text-[#d1d1d1] text-[14px] font-roboto font-medium relative"
              >
                Tự động (
                <span>{{ currentQuality }}</span>
                <span
                  class="text-[#d1d1d1] text-[8px] font-roboto font-medium top-[0px] right-[7px] absolute"
                  >HD</span
                >
                <span class="ml-[12px]"> )</span>
              </p>
              <p
                v-else
                class="text-[#d1d1d1] text-[14px] font-roboto font-medium relative"
              >
                {{ currentQuality }}
              </p>
            </div>

            <div>
              <svg
                height="24"
                viewBox="0 0 24 24"
                width="24"
                focusable="false"
                style="
                  pointer-events: none;
                  display: block;
                  width: 100%;
                  height: 100%;
                  transform: translateY(1px);
                "
              >
                <path
                  fill="#fff"
                  d="m9.4 18.4-.7-.7 5.6-5.6-5.7-5.7.7-.7 6.4 6.4-6.3 6.3z"
                ></path>
              </svg>
            </div>
          </div>
        </div>
      </div>

      <!-- Quality section -->
      <div v-if="isQuality">
        <div
          @click="closeQuality"
          class="w-full h-[45px] flex items-center justify-between px-4 hover:bg-[#686868] transition-all border-b pb-4"
        >
          <div class="flex items-center">
            <i class="fa-solid fa-angle-left text-white block mr-[15px]"></i>
            <p class="text-white text-[15px] font-roboto font-medium">
              Chất lượng
            </p>
          </div>
        </div>
        <div
          class="w-full h-[45px] flex items-center justify-between px-4 hover:bg-[#686868] transition-all"
          v-for="item in props.qualityVideos"
          @click="handleSelectQualityVideo(item)"
        >
          <div class="flex items-center">
            <p class="text-white text-[15px] font-roboto font-medium">
              {{ item.quality }}
            </p>
          </div>
        </div>
      </div>
      <!-- Playbackrate section -->
      <div v-if="isSpeed">
        <div
          @click="closeSpeed"
          class="w-full h-[45px] flex items-center justify-between px-4 hover:bg-[#686868] transition-all border-b pb-4"
        >
          <div class="flex items-center">
            <i class="fa-solid fa-angle-left text-white block mr-[15px]"></i>
            <p class="text-white text-[15px] font-roboto font-medium">
              Tốc độ phát
            </p>
          </div>
        </div>
        <div
          class="w-full h-[45px] flex items-center justify-between px-4 hover:bg-[#686868] transition-all"
          v-for="option in slowOptions"
          @click="HandleChangeVideoSpeed(option.value)"
        >
          <div class="flex items-center">
            <p class="text-white text-[15px] font-roboto font-medium">
              {{ option.value }}
            </p>
          </div>
        </div>
      </div>
      <!-- substitles section -->
      <div v-if="isSubtitles">
        <div
          @click="closeSubtitles"
          class="w-full h-[45px] flex items-center justify-between px-4 hover:bg-[#686868] transition-all border-b pb-4"
        >
          <div class="flex items-center">
            <i class="fa-solid fa-angle-left text-white block mr-[15px]"></i>
            <p class="text-white text-[15px] font-roboto font-medium">Phụ đề</p>
          </div>
        </div>
        <div
          class="w-full h-[45px] flex items-center justify-between px-4 hover:bg-[#686868] transition-all"
          @click="TurnOffSubstitle"
        >
          <div class="flex items-center">
            <p class="text-white text-[15px] font-roboto font-medium">Tắt</p>
          </div>
        </div>
        <div
          class="w-full h-[45px] flex items-center justify-between px-4 hover:bg-[#686868] transition-all"
          v-for="(substitle, index) in state.isDetailVideos.subtitles"
          @click="HandleSelectSubstitles(substitle, index)"
        >
          <div class="flex items-center">
            <p class="text-white text-[15px] font-roboto font-medium">
              {{ substitle.name }}
              <span v-if="substitle.autoGenerated">{đươc tạo tự động}</span>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div
      v-if="isSettings"
      @click="showSettings"
      class="fixed top-0 left-0 right-0 bottom-0 bg-transparent z-10"
    ></div>
  </div>
</template>
